# Generated by Django 4.2.7 on 2026-03-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_competency_lessoncompetency_and_more'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='competencies',
            field=models.ManyToManyField(blank=True, help_text='Competencies assessed by this question', related_name='questions', to='courses.competency'),
        ),
    ]
