# Generated by Django 4.2.7 on 2026-04-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_import_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importhistory',
            new_name='csv_import__teacher_3dd4f8_idx',
            old_name='csv_import__teacher__46a831_idx',
        ),
        migrations.RenameIndex(
            model_name='importhistory',
            new_name='csv_import__course__1d9a7b_idx',
            old_name='csv_import__course_i_9d8f4f_idx',
        ),
        migrations.RenameIndex(
            model_name='importhistory',
            new_name='csv_import__status_d90bf0_idx',
            old_name='csv_import__status_3f5785_idx',
        ),
        migrations.RenameIndex(
            model_name='importrecord',
            new_name='csv_import__import__b55d42_idx',
            old_name='csv_import__import__3b18ab_idx',
        ),
        migrations.RenameIndex(
            model_name='importrecord',
            new_name='csv_import__student_4f492f_idx',
            old_name='csv_import__student_2e4b8f_idx',
        ),
        migrations.RenameIndex(
            model_name='importrecord',
            new_name='csv_import__assessm_91ac5a_idx',
            old_name='csv_import__assessm_8f74c6_idx',
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='error_log',
            field=models.JSONField(default=list, help_text='List of errors encountered during import'),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='original_file',
            field=models.FileField(help_text='Stored original CSV file for audit trail', upload_to='csv_imports/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='students_affected',
            field=models.JSONField(default=list, help_text='List of student IDs whose risk scores were recalculated'),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='message',
            field=models.TextField(blank=True, help_text='Error message or success note'),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='original_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original score before edit', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='raw_data',
            field=models.JSONField(help_text='Original CSV row data'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('MIXED', 'Mixed Questions'), ('EXTERNAL', 'External/Imported')], default='MCQ', max_length=20),
        ),
    ]
