# Generated by Django 4.2.10 on 2026-02-13 09:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('DROPOUT', 'Dropout Risk'), ('PERFORMANCE_DROP', 'Performance Drop'), ('DISENGAGEMENT', 'Disengagement'), ('MULTIPLE_FAILURES', 'Multiple Failures'), ('BEHIND_SCHEDULE', 'Behind Schedule'), ('CUSTOM', 'Custom Alert')], max_length=30)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('engagement_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('progress_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('intervention_notes', models.TextField(blank=True)),
                ('intervention_outcome', models.TextField(blank=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='courses.course')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='courses.enrollment')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='alerts_triggered', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='alerts_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.DecimalField(decimal_places=3, help_text='0.000 = No risk, 1.000 = Critical risk', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('performance_score', models.DecimalField(decimal_places=3, default=0, help_text='0-1, higher = better performance', max_digits=4)),
                ('progress_score', models.DecimalField(decimal_places=3, default=0, help_text='0-1, higher = better progress', max_digits=4)),
                ('engagement_score', models.DecimalField(decimal_places=3, default=0, help_text='0-1, higher = more engaged', max_digits=4)),
                ('contributing_factors', models.JSONField(default=dict, help_text='Factors that influenced this risk score')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_history', to='courses.course')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_history', to='courses.enrollment')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='risk_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_history',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['student', '-calculated_at'], name='risk_histor_student_7dc2ae_idx'), models.Index(fields=['course', 'risk_level'], name='risk_histor_course__094ab2_idx'), models.Index(fields=['enrollment', '-calculated_at'], name='risk_histor_enrollm_f38fdd_idx'), models.Index(fields=['calculated_at'], name='risk_histor_calcula_cda274_idx')],
            },
        ),
        migrations.CreateModel(
            name='LessonInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('VIEW', 'Viewed'), ('COMPLETE', 'Completed'), ('START', 'Started'), ('PAUSE', 'Paused'), ('REWIND', 'Rewound'), ('FORWARD', 'Forward')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('position_seconds', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_interactions', to='courses.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_interactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', '-timestamp'], name='lesson_inte_student_47bdb1_idx'), models.Index(fields=['lesson', 'interaction_type'], name='lesson_inte_lesson__0fd04d_idx'), models.Index(fields=['timestamp'], name='lesson_inte_timesta_7753e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='LessonDifficulty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('failure_rate', models.DecimalField(decimal_places=3, default=0, help_text='0-1, proportion of students who failed', max_digits=4)),
                ('attempt_intensity', models.DecimalField(decimal_places=3, default=0, help_text='0-1, normalized average attempts per student', max_digits=4)),
                ('access_frequency', models.DecimalField(decimal_places=3, default=0, help_text='0-1, normalized views vs expected', max_digits=4)),
                ('time_spent_ratio', models.DecimalField(decimal_places=3, default=0, help_text='0-1, actual time vs estimated time', max_digits=4)),
                ('difficulty_score', models.DecimalField(decimal_places=3, default=0, help_text='0-1, higher = more difficult', max_digits=4)),
                ('difficulty_level', models.CharField(choices=[('VERY_EASY', 'Very Easy'), ('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('VERY_HARD', 'Very Hard'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('unique_students', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_analysis', to='courses.lesson')),
            ],
            options={
                'db_table': 'lesson_difficulty',
                'indexes': [models.Index(fields=['difficulty_level'], name='lesson_diff_difficu_83cd6f_idx'), models.Index(fields=['-difficulty_score'], name='lesson_diff_difficu_f0d476_idx')],
            },
        ),
        migrations.CreateModel(
            name='InterventionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intervention_type', models.CharField(choices=[('EMAIL', 'Email'), ('MESSAGE', 'In-app Message'), ('MEETING', 'One-on-One Meeting'), ('RESOURCE', 'Extra Resources'), ('EXTENSION', 'Deadline Extension'), ('REMEDIATION', 'Remedial Assignment'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('intervention_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Successful - Improved'), ('PARTIAL', 'Partial - Some Improvement'), ('UNCHANGED', 'No Change'), ('WORSENED', 'Worsened'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('outcome_notes', models.TextField(blank=True)),
                ('risk_before', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('risk_after', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('improvement_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='analytics.alert')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions_received', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intervention_log',
                'ordering': ['-intervention_date'],
                'indexes': [models.Index(fields=['teacher', '-intervention_date'], name='interventio_teacher_15bbef_idx'), models.Index(fields=['student', 'outcome'], name='interventio_student_200320_idx'), models.Index(fields=['intervention_type'], name='interventio_interve_9e1596_idx')],
            },
        ),
        migrations.CreateModel(
            name='EngagementMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('week', models.PositiveIntegerField(default=0)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('lessons_viewed', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('quiz_attempts', models.PositiveIntegerField(default=0)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('activity_frequency', models.DecimalField(decimal_places=3, default=0, help_text='0-1, normalized login frequency', max_digits=4)),
                ('completion_rate', models.DecimalField(decimal_places=3, default=0, help_text='0-1, lessons completed vs assigned', max_digits=4)),
                ('quiz_participation', models.DecimalField(decimal_places=3, default=0, help_text='0-1, quiz attempts vs available', max_digits=4)),
                ('engagement_score', models.DecimalField(decimal_places=3, default=0, help_text='0-1 composite score', max_digits=4)),
                ('engagement_level', models.CharField(choices=[('HIGH', 'Highly Engaged'), ('MEDIUM', 'Moderately Engaged'), ('LOW', 'Disengaged'), ('INACTIVE', 'Inactive')], default='LOW', max_length=20)),
                ('trend_direction', models.CharField(choices=[('IMPROVING', 'Improving'), ('DECLINING', 'Declining'), ('STABLE', 'Stable'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='courses.course')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='courses.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'engagement_metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['student', '-date'], name='engagement__student_f61962_idx'), models.Index(fields=['course', 'engagement_level'], name='engagement__course__c14ee7_idx'), models.Index(fields=['date'], name='engagement__date_556b38_idx')],
                'unique_together': {('student', 'course', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['teacher', '-generated_at'], name='alerts_teacher_2aedf9_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['student', 'status'], name='alerts_student_2da014_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'severity'], name='alerts_status_5203b6_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type'], name='alerts_alert_t_eda531_idx'),
        ),
    ]
