# Generated by Django 4.2.7 on 2026-03-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoninteraction',
            name='time_on_page_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Seconds student spent on this lesson (tracked on exit/complete)', null=True),
        ),
        migrations.AlterField(
            model_name='lessondifficulty',
            name='difficulty_level',
            field=models.CharField(choices=[('LOW', 'Low Difficulty'), ('MEDIUM', 'Medium'), ('HIGH', 'High Difficulty'), ('VERY_EASY', 'Very Easy'), ('EASY', 'Easy'), ('HARD', 'Hard'), ('VERY_HARD', 'Very Hard'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
