# Generated by Django 4.2.7 on 2026-03-31 11:47

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_competency_lessoncompetency_and_more'),
        ('analytics', '0002_lessoninteraction_time_on_page_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of correctly answered questions for this competency', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attempts_count', models.PositiveIntegerField(default=0, help_text='Total number of questions answered for this competency')),
                ('correct_count', models.PositiveIntegerField(default=0, help_text='Number of questions answered correctly')),
                ('proficiency_level', models.CharField(choices=[('NOVICE', 'Novice'), ('DEVELOPING', 'Developing'), ('PROFICIENT', 'Proficient'), ('ADVANCED', 'Advanced'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Proficiency level based on score_percentage', max_length=20)),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to='courses.competency')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_performances', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_performances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competency_performance',
                'indexes': [models.Index(fields=['student', 'course'], name='competency__student_18ebd6_idx'), models.Index(fields=['competency', 'proficiency_level'], name='competency__compete_fc665f_idx'), models.Index(fields=['student', '-last_updated'], name='competency__student_642cb8_idx')],
                'unique_together': {('student', 'competency', 'course')},
            },
        ),
    ]
