# Generated by Django 4.2.7 on 2026-03-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_enrollment_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_html',
            field=models.TextField(blank=True, help_text='Rich HTML content for native text editor (replaces content_text)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='icon_color',
            field=models.CharField(blank=True, default='', help_text='Color for UI badge (auto-set based on content_type)', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='word_count_estimated',
            field=models.PositiveIntegerField(default=0, help_text='Auto-calculated word count from content_html'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Auto-estimated or manually set. If None, calculated from content.', null=True),
        ),
    ]
