# Generated by Django 4.2.7 on 2026-03-31 11:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_content_html_lesson_icon_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, help_text="e.g., 'Math', 'Reading', 'Problem Solving'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='courses.course')),
            ],
            options={
                'db_table': 'competencies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LessonCompetency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='0-1, importance of this competency in the lesson', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_mappings', to='courses.competency')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_mappings', to='courses.lesson')),
            ],
            options={
                'db_table': 'lesson_competencies',
                'indexes': [models.Index(fields=['lesson'], name='lesson_comp_lesson__20a23e_idx'), models.Index(fields=['competency'], name='lesson_comp_compete_1eb89d_idx')],
                'unique_together': {('lesson', 'competency')},
            },
        ),
        migrations.AddIndex(
            model_name='competency',
            index=models.Index(fields=['course', 'category'], name='competencie_course__bf75a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competency',
            unique_together={('course', 'name')},
        ),
    ]
